apiVersion: v1
kind: Service
metadata:
  name: celery-flower
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: celery-flower
  ports:
    - name: http
      port: {{ .Values.flower.port }}
      targetPort: {{ .Values.flower.port }}
